version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_host
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    restart: always
  service_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres